/**
 * Core Task entity for the Mini Task Tracker.
 *
 * - `id` is a client-generated UUID (crypto.randomUUID).
 * - `dueDate` is ISO-8601 string (nullable – not every task needs a deadline).
 * - `createdAt` / `updatedAt` are ISO-8601 timestamps set automatically.
 */

export type TaskStatus = "open" | "completed";

export type TaskPriority = "low" | "medium" | "high";

export interface Task {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Payload for creating a new task.
 * `id`, `createdAt`, and `updatedAt` are generated by the app, so they are
 * omitted from the creation input. `status` defaults to "open".
 */
export type CreateTaskInput = Omit<Task, "id" | "createdAt" | "updatedAt" | "status">;

/**
 * Payload for updating an existing task. All fields are optional
 * except the implicit requirement that at least one field changes.
 */
export type UpdateTaskInput = Partial<Omit<Task, "id" | "createdAt" | "updatedAt">>;
